apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-task-api-loadtest
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loadtest
          image: busybox
          command:
            - sh
            - -c
            - |
              i=0
              while [ $i -lt 1000 ]; do
                wget --header='Host: api.noveycloud.com' -q -O- http://cloud-task-api-service/health/ >/dev/null
                i=$((i+1))
              done