apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-task-api
  template:
    metadata:
      labels:
        app: cloud-task-api
    spec:
      containers:
      - name: api
        image: 766158721264.dkr.ecr.us-east-1.amazonaws.com/cloud-task-api:4c1e056634b31dac22d55cc738eb112eb9994a5e
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: cloud-task-api-config
        - secretRef:
            name: cloud-task-api-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
