apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-task-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloud-task-api

  template:
    metadata:
      labels:
        app: cloud-task-api

    spec:
      containers:
      - name: api
        image: cloud-task-api:prod
        ports:
        - containerPort: 8000

        env:
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"