apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-task-api-config
  namespace: staging
data:
  DJANGO_ALLOWED_HOSTS: "staging-api.noveycloud.com, localhost, 127.0.0.1"
  DJANGO_DEBUG: "False"
  SENTRY_ENVIRONMENT: "staging"
  DJANGO_SETTINGS_MODULE: "config.settings"