name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cloud-task-api
  EKS_CLUSTER_NAME: cloud-task-api-eks
  K8S_NAMESPACE: default
  DEPLOYMENT_NAME: cloud-task-api
  CONTAINER_NAME: api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_URI=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME
      
      - name: Debug EKS auth
        run: |
          aws sts get-caller-identity
          kubectl config current-context
          kubectl auth can-i get pods -A || true
          kubectl get nodes    

      - name: Verify cluster access
        run: |
          kubectl config current-context
          kubectl get nodes
      
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Update deployment image
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_URI \
            -n $K8S_NAMESPACE
      
      - name: Veriy rollout
        run: |
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE
      
      - name: Verify health endpoint
        run: |
          curl --fail --silent --show-error \
            --retry 20 \
            --retry-delay 10 \
            --retry-connrefused \
            https://api.noveycloud.com/health/    
      
      - name: Debug on failure
        if: failure()
        run: |
          kubectl get pods -n $K8S_NAMESPACE -o wide
          kubectl describe deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE
          kubectl describe pod -n $K8S_NAMESPACE -l app=$DEPLOYMENT_NAME || true